### DISCUSSION TITLE
Is the level placeholder from an Alarm the measurement before the filter has been applied?

### DISCUSSION THREAD

**Discussion by cascandaliato** [flo-at/minmon#194] [Q&A]
I have this memory check in place and I use the `level` placeholder in my action but I get notified for values below the alarm level (e.g. `65%`).
```toml
[[checks]]
name                 = "memory usage"
type                 = "MemoryUsage"
interval             = 60
memory               = true
[[checks.alarms]]
name                 = "memory usage < 90%"
level                = 90
filter               = {"type" = "Average", "window_size" = 5}
action               = "Notify problem"
```
