### DISCUSSION TITLE
Cannot check FileUsage

### DISCUSSION THREAD

**Discussion by r00tr4v3n** [flo-at/minmon#245] [Q&A] [answered]
Hi, what settings do I need for a file usage check?

```
minmon_1         | 2025-03-08T17:31:41Z [WARN] Check 'Filesystem usage' got no data for id '/dev/sda1': Call to 'statvfs' failed: ENOENT: No such file or directory
minmon_1         | 2025-03-08T17:31:41Z [ERROR] Alarm 'Warning', id '/dev/sda1' from check 'Filesystem usage' got an error: Call to 'statvfs' failed: ENOENT: No such file or directory

```

```
  minmon:
    image: ghcr.io/flo-at/minmon:latest
    volumes:
      - ./minmon.toml:/etc/minmon.toml:ro
      - /mnt/sda1:/mnt/sda1:ro

```
