### ISSUE TITLE
Improve documentation for example config(s)

### ISSUE THREAD

**Issue by lebergarrett** [flo-at/minmon#64]
I'm very interested in trying out MinMon to monitor my selfhosted servers, but it is not very clear to me how I can set up `/etc/minmon.toml` to have multiple checks/alarms/actions. It could very well just be my lack of experience/understanding of TOML, though I still think it would be beneficial for possible users to have some more examples.

For instance, when I see the example given in the README, It's very unclear how I could adapt it to have multiple checks

```toml
[[checks]]
interval = 60
name = "Filesystem usage"
type = "FilesystemUsage"
mountpoints = ["/home"]
```

If I understand correctly, this just correlates to a simple hashmap, which would prevent me from declaring the "name" key multiple times (to create additional checks). Do we create nested hashmaps, how do we name them (maybe `[[checks.FilesystemUsage]]`)?
